title: Daniel Naftel
author: Daniel Naftel
email: naftel.1[at]osu.edu
description: I am a PhD Candidate in the Department of Political Science at Ohio State University. 
  My work investigates the political effects of the criminal justice system, 
  as well as the causes and consequences of inequalities in political voice and the provision of public services.
url: dnaftel/dnaftel.github.io
#baseurl: "/jekyll-theme-kagami"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: dnaftel
twitter_username: DanielNaftel
instagram_username: 

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
