title: 
author: Daniel Naftel
email: naftel.1[at]osu.edu
#description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: dnaftel/dnaftel.github.io
#baseurl: "/jekyll-theme-kagami"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: dnaftel
twitter_username: DanielNaftel
instagram_username: 

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
